---
title: "calvi"
output: html_document
---
```{r, message=FALSE, warning=FALSE}
# initializing
#rm(list = ls())
library(jsonlite)
library(dplyr)
library(ggplot2)
library(boot)
library(tidyr)
library(patchwork)
set.seed(10387)
data = fromJSON("calvi.json")
```

```{r}
data.processed = data %>% filter(stringr::str_detect(description, "expert"))
data.processed$geq3 = data.processed$answer$score >= 3
CVI <- data.processed %>%
  group_by(description) %>%
  summarise(cvi = mean(geq3, na.rm = TRUE))
#CVI.revision = filter(CVI, cvi<0.78)
CVI.revision = filter(CVI, cvi<1)
```

```{r}
#positive:need revision, see source paper
#LLM_predict\actual    P    N
#    P               TP=0  FP=1
#    N               FN=16 TN=32
#precision = 0/1
#recall = 0/16

# Note that CVI threshold is developed through human evaluation. If we change the threshold of CVI (of agents) to higher values, say, less than 5 out of 5 agents (originally less than 4 out of 5 human experts), the result will become different:
#LLM_predict\actual    P    N
#    P               TP=4  FP=1
#    N               FN=12 TN=32
#precision = 4/5
#recall = 4/16
```

```{r}
data.answer = data %>% filter(stringr::str_detect(data$description,"question")) %>% 
  mutate(
    vague = grepl("vague", description),
    wo_text = grepl("with_question_and_options", description) 
  ) %>%
  group_by(vague, wo_text, description) %>%
  summarise(
    Best = mean(`Best Answer`, na.rm = TRUE),
    Best_SD = sd(`Best Answer`, na.rm = TRUE),
    Misleader = mean(`Wrong-Due-To-Misleader Answer`, na.rm = TRUE),
    Misleader_SD = sd(`Wrong-Due-To-Misleader Answer`, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  ungroup()

for (i in 1:nrow(data.answer)) {
  best_ratio <- data.answer$Best[i]
  misleader_ratio <- data.answer$Misleader[i]
  other_ratio <- 1 - best_ratio - misleader_ratio
  if (best_ratio > misleader_ratio && best_ratio > other_ratio) {
    data.answer$Best[i] <- 1
    data.answer$Misleader[i] <- 0
  } else if (misleader_ratio > best_ratio && misleader_ratio > other_ratio) {
    data.answer$Best[i] <- 0
    data.answer$Misleader[i] <- 1
  } else if (other_ratio > best_ratio && other_ratio > misleader_ratio) {
    data.answer$Best[i] <- 0
    data.answer$Misleader[i] <- 0
  } else if (best_ratio == misleader_ratio && best_ratio > other_ratio) {
    data.answer$Best[i] <- 0.5
    data.answer$Misleader[i] <- 0.5
  } else if (best_ratio == other_ratio && best_ratio > misleader_ratio) {
    data.answer$Best[i] <- 0.5
    data.answer$Misleader[i] <- 0
  } else if (misleader_ratio == other_ratio && misleader_ratio > best_ratio) {
    data.answer$Best[i] <- 0
    data.answer$Misleader[i] <- 0.5
  } else if (best_ratio == misleader_ratio && best_ratio == other_ratio) {
    data.answer$Best[i] <- 1/3
    data.answer$Misleader[i] <- 1/3
  }
}


data.answer.formal = data.answer %>% filter(vague==FALSE & wo_text==FALSE)
data.answer.vague = data.answer %>% filter(vague==TRUE & wo_text==FALSE)
data.answer.wo = data.answer %>% filter(vague==FALSE & wo_text==TRUE)
data.answer.vague.wo = data.answer %>% filter(vague==TRUE & wo_text==TRUE)
```

```{r}
data.stat = data.answer %>% group_by(vague, wo_text)%>%
  summarise(
    Best = mean(`Best`, na.rm = TRUE),
    Misleader = mean(`Misleader`, na.rm = TRUE),
    .groups = "drop"
  )
data.stat$image_type <- ifelse(data.stat$vague == TRUE, "vague", "original")
data.stat$text <- ifelse(data.stat$wo_text == TRUE, "w/o text", "w/ text")
data.stat$text <- factor(data.stat$text,levels = c("w/o text", "w/ text"))
data.stat = data.stat %>% reshape2::melt(measure.vars = c("Best", "Misleader"), variable.name = "answer", value.name = "accuracy")

p1 = ggplot(data.stat %>% filter(answer=="Best"), aes(x = image_type, y = accuracy)) +
  geom_bar(stat = "identity",fill="#C6E9F6") +
  theme_minimal() +
  ylim(0,1)+
  labs(x = "", y = "Accuracy") +
  facet_wrap(~text, scales = "free_x",ncol = 2, strip.position = "bottom") +
  theme(strip.placement = "outside")

p2 = ggplot(data.stat %>% filter(answer=="Misleader"), aes(x = image_type, y = accuracy)) +
  geom_bar(stat = "identity",fill="#87CEFA") +
  theme_minimal() +
  ylim(0,1)+
  labs(x = "", y = "Accuracy") +
  facet_wrap(~text, scales = "free_x",ncol = 2, strip.position = "bottom") +
  theme(strip.placement = "outside")

p3 = ggplot(data.stat, aes(x = image_type, y = accuracy, fill = answer)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  ylim(0,1)+
  labs(x = "", y = "Accuracy") +
  facet_wrap(~text, scales = "free_x",ncol = 2, strip.position = "bottom") +
  theme(strip.placement = "outside") +
  scale_fill_manual(values = c("#C6E9F6", "#87CEFA"))+
  theme(legend.title = element_blank())

print(p1 + p2 + p3)
#ggsave(filename = "plot.png",plot = p1 + p2 + p3, width = 10)
```
